$emDash = [char]0x2014
$renames = @{
    "DOCUMENT $emDash EXTENDED DEVELOPMENT ROA V2.txt" = "extended-development-roadmap-v2.txt"
    "DOCUMENT - MINIMUM FEATURE SET FOR V2.txt" = "minimum-feature-set-v2.txt"
    "DOCUMENT 1 - PROJECT VISION & OBJEC V2.txt" = "project-vision-and-objectives-v2.txt"
    "DOCUMENT 2 - GLOBAL ARCHITECTURE V2.txt" = "global-architecture-v2.txt"
    "DOCUMENT 3 - PROMPT ENGINEERING GUI V2.txt" = "prompt-engineering-gui-v2.txt"
    "DOCUMENT 4 - STYLE & COHERENCE BIBL V2.txt" = "style-and-coherence-bibliography-v2.txt"
    "DOCUMENT 5 - QA PROTOCOL V2.txt" = "qa-protocol-v2.txt"
    "DOCUMENT 6 - STORYBOARD TEMPLATE V2.txt" = "storyboard-template-v2.txt"
    "DOCUMENT 7 - PITCH DECK HACKATHON V2.txt" = "pitch-deck-hackathon-v2.txt"
    "DOCUMENT 8 - STORYBOARD EXAMPLE FI V2.txt" = "storyboard-example-file-v2.txt"
    "DOCUMENT 9 - SCENE BREAKDOWN TEMPLA V2.txt" = "scene-breakdown-template-v2.txt"
    "DOCUMENT 10 - SHOT LIST TEMPLATE V2.txt" = "shot-list-template-v2.txt"
    "DOCUMENT 11 - CHARACTER SHEET TEMPL V2.txt" = "character-sheet-template-v2.txt"
    "DOCUMENT 12 - PALETTE & LIGHTING GU V2.txt" = "palette-and-lighting-guide-v2.txt"
    "DOCUMENT 13 - CAMERA LANGUAGE GUIDE V2.txt" = "camera-language-guide-v2.txt"
    "DOCUMENT 14 - PUPPET & LAYER ANNOTA V2.txt" = "puppet-and-layer-annotation-v2.txt"
    "DOCUMENT 16 - COMFYUI WORKFLOW SPEC V2.txt" = "comfyui-workflow-specification-v2.txt"
    "DOCUMENT 17 - FINETUNE STRATEGY  V2.txt" = "finetune-strategy-v2.txt"
    "DOCUMENT 18 - PERSPECTIVE MASTER GU V2.txt" = "perspective-master-guide-v2.txt"
    "DOCUMENT 19 - ACTION & MOTION ENCOD V2.txt" = "action-and-motion-encoding-v2.txt"
    "DOCUMENT 19b - STYLE AND TONE GUIDE V2.txt" = "style-and-tone-guide-v2.txt"
    "DOCUMENT 20 - MULTIMODAL JSON CONTR V2.txt" = "multimodal-json-contract-v2.txt"
    "DOCUMENT 21 - AUDIO & SPATIALIZATIO V2.txt" = "audio-and-spatialization-v2.txt"
    "DOCUMENT 21 b- NARRATIVE STRUCTURE GUIDE V2.txt" = "narrative-structure-guide-v2.txt"
    "DOCUMENT 22 - ENVIRONMENT DESIGN GU V2.txt" = "environment-design-guide-v2.txt"
    "DOCUMENT 22b - SCENE CONSTRUCTION GUIDE V2.txt" = "scene-construction-guide-v2.txt"
    "DOCUMENT 23 - SCENE TRANSITION & CO V2.txt" = "scene-transition-and-continuity-v2.txt"
    "DOCUMENT 23b - CHARACTER ARC GUIDE V2.txt" = "character-arc-guide-v2.txt"
    "DOCUMENT 24 - GLOBAL PIPELINE ARCHI V2.txt" = "global-pipeline-architecture-v2.txt"
    "DOCUMENT 24b - DIALOGUE CONSTRUCTION GUIDE V2.txt" = "dialogue-construction-guide-v2.txt"
    "DOCUMENT 25 - STORYBOARD DRAWING RU V2.txt" = "storyboard-drawing-rules-v2.txt"
    "DOCUMENT 25b - CAMERA DIRECTION & CINEMATIC FRAMING GUIDE V2.txt" = "camera-direction-and-cinematic-framing-guide-v2.txt"
    "DOCUMENT 26 - CHARACTER INTERACTION V2.txt" = "character-interaction-v2.txt"
    "DOCUMENT 26b - LIGHTING DIRECTION & CINEMATIC ILLUMINATION GUIDE V2.txt" = "lighting-direction-and-cinematic-illumination-guide-v2.txt"
    "DOCUMENT 27 - CINEMATIC LIGHTING SC V2.txt" = "cinematic-lighting-scenarios-v2.txt"
    "DOCUMENT 27 b- CINEMATIC LIGHTING SCENARIOS GUIDE V2.txt" = "cinematic-lighting-scenarios-guide-v2.txt"
    "DOCUMENT 28 - VIDEO INTERPOLATION & V2.txt" = "video-interpolation-and-effects-v2.txt"
    "DOCUMENT 29 - COLOR GRADING & LOOK V2.txt" = "color-grading-and-look-v2.txt"
    "DOCUMENT 30 - CHARACTER EMOTION & E V2.txt" = "character-emotion-and-expression-v2.txt"
    "DOCUMENT 31 - CAMERA MOVEMENT & CIN V2.txt" = "camera-movement-and-cinematography-v2.txt"
    "DOCUMENT 32 - MULTIMODAL QA MASTER V2.txt" = "multimodal-qa-master-v2.txt"
    "DOCUMENT 33 - ANIMATION TIMING & RH V2.txt" = "animation-timing-and-rhythm-v2.txt"
    "DOCUMENT 34 - DIALOGUE, VOICE & PER V2.txt" = "dialogue-voice-and-performance-v2.txt"
    "DOCUMENT 35 - CHARACTER SILHOUETTE V2.txt" = "character-silhouette-v2.txt"
    "DOCUMENT 36 - MULTIMODAL DEBUGGING V2.txt" = "multimodal-debugging-v2.txt"
    "DOCUMENT 37 - WORLDBUILDING & LORE V2.txt" = "worldbuilding-and-lore-v2.txt"
    "DOCUMENT 38 - CHARACTER COSTUME & V V2.txt" = "character-costume-and-visuals-v2.txt"
    "DOCUMENT 39 - ADVANCED PROMPT ENGIN V2.txt" = "advanced-prompt-engineering-v2.txt"
    "DOCUMENT 40 - ENVIRONMENT PHYSICS & V2.txt" = "environment-physics-and-dynamics-v2.txt"
    "DOCUMENT 41 - MULTIMODAL NARRATIVE V2.txt" = "multimodal-narrative-v2.txt"
    "DOCUMENT 42 - AI-ASSISTED AUTHORING V2.txt" = "ai-assisted-authoring-v2.txt"
    "DOCUMENT 43 - MULTIMODAL ASSET TAXO V2.txt" = "multimodal-asset-taxonomy-v2.txt"
    "DOCUMENT 44 - AUTHOR DASHBOARD & UX V2.txt" = "author-dashboard-and-ux-v2.txt"
    "DOCUMENT 45 - MULTIMODAL DATA SCHEM V2.txt" = "multimodal-data-schema-v2.txt"
    "DOCUMENT 46 - MULTIMODAL PIPELINE P V2.txt" = "multimodal-pipeline-protocol-v2.txt"
    "DOCUMENT 47 - SECURITY, PRIVACY & D V2.txt" = "security-privacy-and-data-v2.txt"
    "DOCUMENT 48 - MULTIMODAL EXPORT & P V2.txt" = "multimodal-export-and-publishing-v2.txt"
    "DOCUMENT 49 - COLLABORATION, BRANCH V2.txt" = "collaboration-and-branching-v2.txt"
    "DOCUMENT 50 - FULL PIPELINE MASTER V2.txt" = "full-pipeline-master-v2.txt"
    "DOCUMENT 51 - DATA CONTRACT SPECIFI V2.txt" = "data-contract-specification-v2.txt"
    "DOCUMENT 52 - THE PROMOTION PIPELIN V2.txt" = "promotion-pipeline-v2.txt"
    "DOCUMENT 53 - QA & REGENERATION LOO V2.txt" = "qa-and-regeneration-loop-v2.txt"
    "StoryCore-Engine - Requirements Spe V2.txt" = "storycore-engine-requirements-spec-v2.txt"
    "StoryCore-Engine - Vision Code V2.txt" = "storycore-engine-vision-code-v2.txt"
}

foreach ($old in $renames.Keys) {
    $new = $renames[$old]
    $oldPath = ".kiro\docs\Docs initiales\$old"
    if (Test-Path $oldPath) {
        Rename-Item $oldPath $new
        Write-Host "Renamed $old to $new"
    } else {
        Write-Host "File not found: $oldPath"
    }
}