"""
Recursive Language Model (RLM) Engine for StoryCore Assistant.

This module provides a framework for advanced context management and recursive 
problem solving, inspired by the RLM concept. It transforms passive context ingestion
into an active exploration and synthesis process, ideal for complex tasks like
story generation, complex dialogues, and scenario structuring.
"""

import ast
import operator
import re
import asyncio
import math as py_math
import json as py_json
import re as py_re
from typing import Any, Dict, List, Callable, Optional, Union, Awaitable, Tuple
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from io import StringIO
import contextlib
from .knowledge_graph import StoryGraph, GraphRAG

@dataclass
class RLMSubtask:
    """Represents a decomposed subtask to be solved recursively."""
    id: str
    description: str
    context_slice_ref: Optional[str] = None
    result: Optional[str] = None
    status: str = "pending"

class SecurityValidator(ast.NodeVisitor):
    """
    Validates AST to prevent dangerous operations like importing system modules.
    """
    def visit_Import(self, node):
        raise SecurityError(f"Imports are not allowed in this restricted environment: {ast.unparse(node)}")
        
    def visit_ImportFrom(self, node):
        raise SecurityError(f"Imports are not allowed in this restricted environment: {ast.unparse(node)}")

class SecurityError(Exception):
    pass

class RestrictedPythonREPL:
    """
    A restricted Python REPL environment to allow the LLM to inspect, slice, 
    and filter the context programmatically without full system access.
    """
    def __init__(self, context_data: str):
        self.variables: Dict[str, Any] = {
            "context": context_data,
            "len": len,
            "print": print,
            "list": list,
            "dict": dict,
            "str": str,
            "int": int,
            "enumerate": enumerate,
            "math": py_math,
            "json": py_json,
            "re": py_re,
            "subtasks": {},
            "n8n_trigger": None,
            "n8n_list_workflows": None,
            "n8n_create_workflow": None
        }

    def execute(self, code: str) -> str:
        """
        Executes a snippet of Python code safely and returns the captured stdout.
        
        Args:
            code: Python code string to execute
            
        Returns:
            The standard output generated by the code
        """
        try:
            # 1. AST Validation for Security (Sandbox)
            parsed_code = ast.parse(code)
            SecurityValidator().visit(parsed_code)
            
            output = StringIO()
            with contextlib.redirect_stdout(output):
                # Basic safety execution limited by globals and AST validation
                exec(code, {"__builtins__": {}}, self.variables)
            return output.getvalue()
        except SecurityError as se:
            return f"Security Error: {str(se)}"
        except Exception as e:
            return f"Error executing code: {str(e)}"
            
    def get_variable(self, name: str) -> Any:
        return self.variables.get(name)

    def set_variable(self, name: str, value: Any):
        self.variables[name] = value

class RLMAgentCore(ABC):
    """
    Base class for the Recursive Language Model Agent.
    """
    @abstractmethod
    async def call_llm(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        """Abstract method to call the underlying LLM."""
        pass

    @abstractmethod
    async def query_database(self, query: str) -> str:
        """
        Abstract method representing the Continuous Vector Memory (RAG + RLM).
        Allows the agent to search external knowledge or previous project data.
        """
        pass

    @abstractmethod
    async def query_graph(self, entities: List[str], max_depth: int = 1) -> str:
        """
        Abstract method representing the Knowledge Graph search (GraphRAG).
        Allows the agent to query semantic relationships and lore continuity.
        """
        pass

    async def run_subtask(self, subtask: RLMSubtask, sub_context: str) -> str:
        """Recursively call the LLM to handle a smaller chunk of the problem."""
        system_prompt = (
            "You are a recursive sub-agent handling a specific subtask. "
            f"Subtask: {subtask.description}\n"
            "Analyze the provided context and return ONLY the result for this subtask."
        )
        prompt = f"Context slice:\n{sub_context}\n\nPlease complete the subtask."
        return await self.call_llm(prompt, system_prompt=system_prompt)

class RLMEngine:
    """
    The orchestrator that runs the RLM loop:
    1. Environment Setup
    2. Active Exploration
    3. Task Decomposition
    4. Recursive Solving (Async)  
    5. Synthesis
    6. Critique-Correction Loop  ← enhanced with GraphRAG
    7. Automation Integration (n8n)
    """
    def __init__(
        self,
        agent_core: RLMAgentCore,
        graph_rag: Optional[GraphRAG] = None,
        on_step_event: Optional[Callable[[str], None]] = None
    ):
        self.agent_core = agent_core
        self.graph_rag = graph_rag          # real GraphRAG — None = fallback to agent.query_graph
        self.max_loops = 10
        self.on_step_event = on_step_event or (lambda x: None)
        self.trajectory: List[str] = []

    def _notify(self, message: str):
        self.trajectory.append(message)
        self.on_step_event(message)

    async def process(self, main_prompt: str, massive_context: str) -> str:
        """Process and return only the final answer."""
        result, _ = await self.process_with_steps(main_prompt, massive_context)
        return result

    async def process_with_steps(self, main_prompt: str, massive_context: str) -> Tuple[str, List[str]]:
        """
        Process a complex prompt against a massive context using the RLM approach.
        Returns both the final answer and the trajectory of internal steps.
        """
        self.trajectory = []
        self._notify("Setting up environment and context variables...")
        repl = RestrictedPythonREPL(massive_context)
        
        system_prompt = (
            "You are an RLM (Recursive Language Model) Agent. "
            "You have access to a massive context stored in the variable `context`. "
            "You can execute python code to explore, filter, or slice this context. "
            "Instead of reading it all passively, you must actively:\n"
            "1. EXPLORE: Write python snippets to print lengths, samples, structure.\n"
            "2. DECOMPOSE: Create subtasks for specific parts.\n"
            "3. SYNTHESIZE: Combine subtask results into the final answer.\n\n"
            "You can use `query_database('query str')` to search long-term memory (RAG).\n"
            "You can also use `query_graph(['Entity A', 'Entity B'], max_depth=2)` to search semantic graph links.\n\n"
            "To execute code, reply with:\n"
            "```python\n# your code here\n```\n"
            "To create a subtask, use `run_subtask(description, context_slice)`.\n"
            "To run multiple subtasks at once, use `run_subtasks_parallel([{'description': '...', 'context_slice': '...'}, ...])`.\n"
            "To trigger an external n8n automation workflow, use `n8n_trigger(webhook_id, {'key': 'value'})`.\n"
            "To list available n8n workflows, use `n8n_list_workflows()`.\n"
            "To create a new n8n workflow, use `n8n_create_workflow(name, nodes, connections)`.\n"
            "To send a notification, use `send_message(platform, text, target_id=None)` where platform is 'telegram' or 'discord'.\n"
            "To check messaging status, use `get_messaging_status()`.\n"
            "To finish, reply with:\n"
            "FINAL_ANSWER: your complete detailed response."
        )
        
        # Inject the recursive capability and DAG functionality into the REPL
        def _repl_subtask(description: str, context_slice: str) -> str:
            subtask = RLMSubtask(id=str(uuid.uuid4())[:8], description=description)
            loop = asyncio.get_event_loop()
            if loop.is_running():
                # If we are already in an async context, we need to schedule this
                # or use nest_asyncio. Given RLMEngine.process is async, 
                # we should try to avoid blocking the loop too much.
                # However, REPL execution is currently synchronous.
                # To truly support parallel, we'll use a specific parallel function.
                import nest_asyncio
                nest_asyncio.apply()
                return loop.run_until_complete(self.agent_core.run_subtask(subtask, context_slice))
            return asyncio.run(self.agent_core.run_subtask(subtask, context_slice))

        def _repl_run_parallel(tasks_data: List[Dict[str, str]]) -> List[str]:
            """
            Executes multiple subtasks in parallel.
            tasks_data format: [{"description": "...", "context_slice": "..."}]
            """
            self._notify(f"Executing {len(tasks_data)} subtasks in parallel...")
            
            async def run_all():
                coros = []
                for data in tasks_data:
                    subtask = RLMSubtask(id=str(uuid.uuid4())[:8], description=data["description"])
                    coros.append(self.agent_core.run_subtask(subtask, data["context_slice"]))
                return await asyncio.gather(*coros)

            loop = asyncio.get_event_loop()
            if loop.is_running():
                import nest_asyncio
                nest_asyncio.apply()
                return loop.run_until_complete(run_all())
            return asyncio.run(run_all())
            
        def _repl_query_db(query: str) -> str:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                import nest_asyncio
                nest_asyncio.apply()
                return loop.run_until_complete(self.agent_core.query_database(query))
            return asyncio.run(self.agent_core.query_database(query))

        def _repl_query_graph(entities: List[str], max_depth: int = 1) -> str:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                import nest_asyncio
                nest_asyncio.apply()
                return loop.run_until_complete(self.agent_core.query_graph(entities, max_depth))
            return asyncio.run(self.agent_core.query_graph(entities, max_depth))

        async def _repl_n8n_trigger(webhook_id: str, payload: Dict[str, Any]) -> str:
            self._notify(f"Triggering n8n workflow: {webhook_id}...")
            # We defer implementation to agent_core if it supports it
            if hasattr(self.agent_core, 'trigger_n8n'):
                res = await self.agent_core.trigger_n8n(webhook_id, payload)
                return py_json.dumps(res)
            return "n8n trigger not supported by this agent core."

        def _repl_n8n_trigger_sync(webhook_id: str, payload: Dict[str, Any]) -> str:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                import nest_asyncio
                nest_asyncio.apply()
                return loop.run_until_complete(_repl_n8n_trigger(webhook_id, payload))
            return asyncio.run(_repl_n8n_trigger(webhook_id, payload))

        async def _repl_n8n_list() -> str:
            self._notify("Listing n8n workflows...")
            if hasattr(self.agent_core, 'list_n8n'):
                res = await self.agent_core.list_n8n()
                return py_json.dumps(res)
            return "n8n list not supported by this agent core."

        def _repl_n8n_list_sync() -> str:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                import nest_asyncio
                nest_asyncio.apply()
                return loop.run_until_complete(_repl_n8n_list())
            return asyncio.run(_repl_n8n_list())

        async def _repl_n8n_create(name: str, nodes: List[Dict[str, Any]], connections: Dict[str, Any]) -> str:
            self._notify(f"Creating n8n workflow: {name}...")
            if hasattr(self.agent_core, 'create_n8n'):
                res = await self.agent_core.create_n8n(name, nodes, connections)
                return py_json.dumps(res)
            return "n8n create not supported by this agent core."

        def _repl_n8n_create_sync(name: str, nodes: List[Dict[str, Any]], connections: Dict[str, Any]) -> str:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                import nest_asyncio
                nest_asyncio.apply()
                return loop.run_until_complete(_repl_n8n_create(name, nodes, connections))
            return asyncio.run(_repl_n8n_create(name, nodes, connections))

        repl.set_variable("run_subtask", _repl_subtask)
        repl.set_variable("run_subtasks_parallel", _repl_run_parallel)
        repl.set_variable("query_database", _repl_query_db)
        repl.set_variable("query_graph", _repl_query_graph)
        repl.set_variable("n8n_trigger", _repl_n8n_trigger_sync)
        repl.set_variable("n8n_list_workflows", _repl_n8n_list_sync)
        repl.set_variable("n8n_create_workflow", _repl_n8n_create_sync)
        
        # Messaging Integration
        async def _repl_send_message(platform: str, text: str, target_id: Optional[str] = None) -> str:
            self._notify(f"Sending {platform} message...")
            if hasattr(self.agent_core, 'send_message'):
                res = await self.agent_core.send_message(platform, text, target_id)
                return py_json.dumps(res)
            return "Messaging not supported by this agent core."

        def _repl_send_message_sync(platform: str, text: str, target_id: Optional[str] = None) -> str:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                import nest_asyncio
                nest_asyncio.apply()
                return loop.run_until_complete(_repl_send_message(platform, text, target_id))
            return asyncio.run(_repl_send_message(platform, text, target_id))

        async def _repl_get_msg_status() -> str:
            if hasattr(self.agent_core, 'get_messaging_status'):
                res = await self.agent_core.get_messaging_status()
                return py_json.dumps(res)
            return "Messaging status not supported by this agent core."

        def _repl_get_msg_status_sync() -> str:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                import nest_asyncio
                nest_asyncio.apply()
                return loop.run_until_complete(_repl_get_msg_status())
            return asyncio.run(_repl_get_msg_status())

        repl.set_variable("send_message", _repl_send_message_sync)
        repl.set_variable("get_messaging_status", _repl_get_msg_status_sync)
        
        # NOTE: Multi-Agent Swarm (Specialization of Sub-Agents)
        # We could route specific subtasks to different expert agents here based on intent analysis.
        # This is not implemented currently (as per user request to save computational resources)
        # but kept as a possibility for a future version if remote/cloud resources are used.
        
        history = f"User Request: {main_prompt}\n"

        for i in range(self.max_loops):
            self._notify(f"Thinking (Iteration {i+1}/{self.max_loops})...")

            response = await self.agent_core.call_llm(history, system_prompt=system_prompt)
            history += f"\nAssistant: {response}\n"

            if "FINAL_ANSWER:" in response:
                draft_answer = response.split("FINAL_ANSWER:")[1].strip()

                # 6. Critique-Correction Loop (Reflection) with GraphRAG
                self._notify("Applying Critique-Correction Loop with GraphRAG...")

                lore_context = ""
                consistency_report = ""

                if self.graph_rag:
                    # --- Real GraphRAG path ---
                    potential_entities = list(set(
                        w for w in re.findall(r'\b[A-Z][a-z]+\b', draft_answer)
                        if len(w) > 2
                    ))
                    if potential_entities:
                        self._notify(f"Querying Knowledge Graph for {len(potential_entities)} entities...")
                        lore_context = "\nGraphRAG Lore Continuity Data:\n" + \
                            self.graph_rag.query(potential_entities[:8], max_depth=1)
                        consistency_report = "\nConsistency Check:\n" + \
                            self.graph_rag.check_consistency(draft_answer)
                else:
                    # --- Fallback: delegate to abstract agent.query_graph ---
                    potential_entities = list(set(
                        w for w in re.findall(r'\b[A-Z][a-z]+\b', draft_answer)
                        if len(w) > 2
                    ))
                    if potential_entities:
                        self._notify(f"Querying Knowledge Graph for entities: {potential_entities[:5]}...")
                        graph_result = await self.agent_core.query_graph(potential_entities[:5], max_depth=1)
                        lore_context = f"\nGraphRAG Lore Continuity Data:\n{graph_result}\n"

                reflection_prompt = (
                    "You are the Critique-Correction module. Read the original request, "
                    "the draft response, and the GraphRAG Lore Data.\n"
                    f"Request: {main_prompt}\n"
                    f"Draft Answer: {draft_answer}\n"
                    f"{lore_context}"
                    f"{consistency_report}\n"
                    "1. Does this draft answer the request accurately?\n"
                    "2. Does it respect the GraphRAG Lore Continuity Data (no plot holes or contradictions)?\n"
                    "If there are flaws, fix them and return the FIXED version.\n"
                    "Always prefix your final approved text with APPROVED_ANSWER:"
                )

                reflection_response = await self.agent_core.call_llm(reflection_prompt)
                if "APPROVED_ANSWER:" in reflection_response:
                    final_answer = reflection_response.split("APPROVED_ANSWER:")[1].strip()
                else:
                    final_answer = reflection_response  # Fallback

                self._notify("Generation complete!")
                return final_answer, self.trajectory

            code_match = re.search(r"```python\n(.*?)```", response, re.DOTALL)
            if code_match:
                code = code_match.group(1)
                self._notify("Executing code snippet for context exploration...")
                execution_output = repl.execute(code)
                history += f"\nEnvironment Result:\n{execution_output}\n"
            else:
                history += "\nSystem: Please either write ```python ... ``` code to explore/decompose, or provide FINAL_ANSWER: with the final result.\n"

        self._notify("Max loops reached, synthesizing fallback answer.")
        return "Error: Reached maximum recursive loops without synthesizing a final answer.", self.trajectory

if __name__ == "__main__":
    import sys
    try:
        import nest_asyncio
        nest_asyncio.apply()
    except ImportError:
        pass

    class MockRLMAgent(RLMAgentCore):
        async def call_llm(self, prompt: str, system_prompt: Optional[str] = None) -> str:
            await asyncio.sleep(0.1) # Simulate async latency
            if "Critique-Correction module" in prompt:
                return "APPROVED_ANSWER: The scenario outline is perfect. I have validated the structure."
                
            if "User Request:" in prompt and "FINAL_ANSWER:" not in prompt and "```python" not in prompt:
                return "```python\nprint(f'Context length: {len(context)}')\nprint(context[:100])\n```"
            elif "Environment Result:" in prompt:
                return "FINAL_ANSWER: I have reviewed the structured elements and prepared the scenario outline based on your request."
            return "FINAL_ANSWER: Mock response."
            
        async def query_database(self, query: str) -> str:
            return f"Found 1 result for '{query}': The character likes coffee."

        async def query_graph(self, entities: List[str], max_depth: int = 1) -> str:
            if not entities:
                return "Graph is empty."
            return f"Graph Relations: '{entities[0]}' main ally is the 'Wizard'. It possesses the 'Ancient Map'."

    async def main():
        def on_step(msg):
            print(f"[UI UPDATE] {msg}")
            
        engine = RLMEngine(agent_core=MockRLMAgent(), on_step_event=on_step)
        epic_context = "Chapter 1: The Beginning... " * 1000
        res = await engine.process("Develop a complex multi-branch dialogue scenario from this script", epic_context)
        print("\nFinal Output:")
        print(res)
        
    asyncio.run(main())
