/**
 * Moodboard and Creative Direction Types
 */

export interface MoodboardReference {
  id: string;
  url: string;
  type: 'image' | 'video' | 'texture' | 'pattern';
  note?: string;
  source?: 'upload' | 'ai-generated' | 'web';
  tags?: string[];
}

export interface MoodboardInspirationNote {
  id: string;
  content: string;
  category: 'atmosphere' | 'lighting' | 'framing' | 'storytelling' | 'general';
  createdAt: number;
}

export interface MoodboardTypography {
  headers: string;
  body: string;
  fontStyles?: string[]; // e.g., ["bold", "italic"]
}

export interface MoodboardVisualStyle {
  artStyle: string; // ex: "Oil painting", "Cyberpunk", "Minimalist"
  colorPalette: string[]; // List of Hex codes
  typography: MoodboardTypography;
  lightingDescription?: string;
  cameraAnglesPresets?: string[];
}

export interface MoodboardVision {
  description: string;
  keywords: string[];
  tone?: string;
  targetAudience?: string;
}

export interface MoodboardData {
  id: string;
  projectId: string;
  vision: MoodboardVision;
  visualStyle: MoodboardVisualStyle;
  references: MoodboardReference[];
  inspirationNotes: MoodboardInspirationNote[];
  updatedAt: number;
}

/**
 * Suggestions generated by IA based on project content
 */
export interface MoodboardSuggestion {
  id: string;
  title: string;
  description: string;
  suggestedStyle: Partial<MoodboardVisualStyle>;
  suggestedVision: Partial<MoodboardVision>;
  reasoning: string; // Why this was suggested
}
