// ============================================================================
// Story Types for Storyteller Wizard
// ============================================================================

/**
 * Main Story interface representing a complete narrative
 */
export interface Story {
  id: string;
  title: string;
  content: string;
  summary: string;
  genre: string[];
  tone: string[];
  length: 'short' | 'medium' | 'long' | 'scene' | 'short_story' | 'novella' | 'novel' | 'epic_novel';
  charactersUsed: CharacterReference[];
  locationsUsed: LocationReference[];
  autoGeneratedElements: AutoGeneratedElement[];
  createdAt: Date;
  updatedAt: Date;
  version: number;
  worldId?: string;
  parts?: StoryPart[]; // For iterative, multi-part generation
}

/**
 * A specific part of an iteratively generated story
 */
export interface StoryPart {
  id: string;
  type: 'intro' | 'chapter' | 'ending';
  title: string;
  content: string;
  summary: string; // Used as context for the next part
  reviewScore?: {
    tension: number;
    drama: number;
    sense: number;
    emotion: number;
    overall: number;
  };
  order: number;
}

/**
 * Reference to a character used in a story
 */
export interface CharacterReference {
  id: string;
  name: string;
  role: string;
}

/**
 * Reference to a location used in a story
 */
export interface LocationReference {
  id: string;
  name: string;
  significance: string;
}

/**
 * Auto-generated element (character or location) created during story generation
 */
export interface AutoGeneratedElement {
  type: 'character' | 'location';
  id: string;
  name: string;
  generatedAt: Date;
}

/**
 * Draft version of a story (incomplete, saved for later)
 */
export interface StoryDraft {
  id: string;
  storyId: string;
  data: Partial<Story>;
  currentStep: number;
  savedAt: Date;
}

/**
 * Version snapshot of a story
 */
export interface StoryVersion {
  id: string;
  storyId: string;
  versionNumber: number;
  content: string;
  summary: string;
  createdAt: Date;
  changes: string;
}

/**
 * Parameters for story generation
 */
export interface StoryGenerationParams {
  genre: string[];
  tone: string[];
  length: 'short' | 'medium' | 'long' | 'scene' | 'short_story' | 'novella' | 'novel' | 'epic_novel';
  characters: any[]; // Character objects from world data
  locations: any[]; // Location objects from world data
  worldContext: WorldContext;
  totalTitle?: string;
}

/**
 * World context for story generation
 */
export interface WorldContext {
  id: string;
  name: string;
  genre: string[];
  tone: string[];
  rules: WorldRule[];
  culturalElements: CulturalElements;
  atmosphere: string;
}

/**
 * World rule definition
 */
export interface WorldRule {
  id: string;
  category: string;
  rule: string;
  description: string;
}

/**
 * Cultural elements of a world
 */
export interface CulturalElements {
  languages?: string[];
  religions?: string[];
  customs?: string[];
  traditions?: string[];
  socialStructure?: string;
}

/**
 * Request to create a new character
 */
export interface CharacterCreationRequest {
  name: string;
  role: string;
  description: string;
}

/**
 * Request to create a new location
 */
export interface LocationCreationRequest {
  name: string;
  type: string;
  description: string;
}

/**
 * Progress tracking for story generation
 */
export interface GenerationProgress {
  stage:
  | 'preparing'
  | 'creating_elements'
  | 'generating_intro'
  | 'generating_chapter'
  | 'generating_ending'
  | 'reviewing'
  | 'refining'
  | 'complete';
  progress: number; // 0-100
  currentTask: string;
  currentChapter?: number;
  totalChapters?: number;
  error?: string;
}

/**
 * Export options for story files
 */
export interface ExportOptions {
  format: 'txt' | 'md';
  includeMetadata: boolean;
  includeSummary: boolean;
  filename: string;
}

/**
 * Story setup data (Step 1)
 */
export interface StorySetupData {
  genre: string[];
  tone: string[];
  length: 'short' | 'medium' | 'long' | 'scene' | 'short_story' | 'novella' | 'novel' | 'epic_novel';
  title?: string;
}

/**
 * Character selection data (Step 2)
 */
export interface CharacterSelectionData {
  selectedCharacters: CharacterReference[];
  newCharactersToCreate: CharacterCreationRequest[];
}

/**
 * Location selection data (Step 3)
 */
export interface LocationSelectionData {
  selectedLocations: LocationReference[];
  newLocationsToCreate: LocationCreationRequest[];
}

// ============================================================================
// Legacy Story Types (kept for backward compatibility)
// ============================================================================

export interface StorySummary {
  id: string;
  title: string;
  genre: string[];
  tone: string[];
  targetAudience: string;
  videoType: 'court-métrage' | 'métrage' | 'série-episode' | 'web-série';
  duration: number; // minutes
  acts: StoryAct[];
  keyCharacters: string[];
  mainConflict: string;
  resolution: string;
  themes: string[];
  selectedVisualStyle: string; // Style choisi par l'utilisateur
  recommendedVisualStyle: string; // Style recommandé par l'IA
  pacing: string;
  musicSuggestions?: string[]; // Suggestions musicales
  moodPalette?: string[]; // Palette de couleurs d'ambiance
  cameraTechniques?: string[]; // Techniques de caméra suggérées
  createdAt: Date;
  basedOnPreviousEpisode?: string;
  worldContext: string;
}

export interface StoryAct {
  id: string;
  number: number;
  title: string;
  description: string;
  keyScenes: string[];
  characterDevelopment: string;
  duration: number; // minutes
}

export interface StoryContext {
  characters: any[]; // From project characters
  world: any; // From project world
  locations: any[]; // From project locations
  previousEpisodes: any[]; // Previous story summaries
  userPreferences: {
    preferredGenres: string[];
    preferredVideoType: string;
    preferredDuration: number;
    preferredTone: string[];
  };
}

export interface StorytellerWizardData {
  // Context analysis
  selectedCharacters: string[];
  selectedLocations: string[];
  previousEpisodeReference: string;

  // Story parameters
  videoType: 'court-métrage' | 'métrage' | 'série-episode' | 'web-série';
  targetDuration: number;
  genre: string[];
  tone: string[];
  targetAudience: string;
  visualStyle: string;

  // Generated content
  storySummary: string;
  mainConflict: string;
  resolution: string;
  themes: string[];
  acts: StoryAct[];
  recommendedVisualStyle: string; // Style visuel recommandé par l'IA
  pacing: string;
  musicSuggestions?: string[]; // Suggestions musicales
  moodPalette?: string[]; // Palette de couleurs d'ambiance
  cameraTechniques?: string[]; // Techniques de caméra suggérées

  // Validation
  isValidated: boolean;
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Create an empty story with default values
 */
export function createEmptyStory(): Partial<Story> {
  return {
    id: crypto.randomUUID(),
    title: '',
    content: '',
    summary: '',
    genre: [],
    tone: [],
    length: 'medium',
    charactersUsed: [],
    locationsUsed: [],
    autoGeneratedElements: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    version: 1,
  };
}

/**
 * Check if a story is complete (has all required fields)
 */
export function isStoryComplete(story: Partial<Story>): story is Story {
  return !!(
    story.id &&
    story.title &&
    story.content &&
    story.summary &&
    story.genre &&
    story.genre.length > 0 &&
    story.tone &&
    story.tone.length > 0 &&
    story.length &&
    story.charactersUsed &&
    story.locationsUsed &&
    story.autoGeneratedElements !== undefined &&
    story.createdAt &&
    story.updatedAt &&
    story.version
  );
}