import React, { useState, useCallback, useMemo } from 'react';
import { WizardErrorBoundary } from '../WizardErrorBoundary';
import { WizardStepIndicator, WizardStep } from '../WizardStepIndicator';
import { WizardNavigation } from '../WizardNavigation';
import { useStore } from '@/store';
import { useAppStore } from '@/stores/useAppStore';
import { saveWizardState } from '@/utils/wizardStorage';
import type { Story } from '@/types/story';

// Subcomponents
import { FoundationsStep, PlotArchitectureStep, CharacterArcsStep } from './steps';

export interface ScenarioBuilderWizardProps {
  onComplete: (data: Partial<Story>) => void;
  onCancel: () => void;
  initialData?: Partial<Story>;
}

export function ScenarioBuilderWizard({
  onComplete,
  onCancel,
  initialData,
}: ScenarioBuilderWizardProps) {
  // State
  const [currentStep, setCurrentStep] = useState(1);
  const [data, setData] = useState<Partial<Story>>(initialData || {
    title: '',
    logline: '',
    genre: [],
    tone: [],
    acts: [],
    charactersUsed: [],
    autoGeneratedElements: [],
  });
  const [lastSaved, setLastSaved] = useState<Date | undefined>();

  const addStory = useStore((state) => state.addStory);
  const setShowScenarioBuilder = useAppStore(state => state.setShowScenarioBuilder);

  // Steps definition
  const steps: WizardStep[] = [
    { number: 1, title: 'Foundations', description: 'Story Identity' },
    { number: 2, title: 'Architecture', description: 'Act Structure' },
    { number: 3, title: 'Character Arcs', description: 'Cast & Roles' },
  ];

  // Data update
  const updateData = useCallback((newData: Partial<Story>) => {
    setData((prev) => ({ ...prev, ...newData }));
  }, []);

  const handleFinish = useCallback(async () => {
    const finalStory = {
      ...data,
      id: crypto.randomUUID(),
      createdAt: Date.now(),
      updatedAt: Date.now(),
      version: 1,
    } as Story;
    
    addStory(finalStory);
    onComplete(finalStory);
    setShowScenarioBuilder(false);
  }, [data, onComplete, addStory, setShowScenarioBuilder]);

  // Render current step content
  const stepContent = useMemo(() => {
    switch (currentStep) {
      case 1:
        return (
          <FoundationsStep 
            data={data} 
            onUpdate={updateData} 
          />
        );
      case 2:
        return (
          <PlotArchitectureStep 
            data={data} 
            onUpdate={updateData} 
          />
        );
      case 3:
        return (
          <CharacterArcsStep 
            data={data} 
            onUpdate={updateData} 
          />
        );
      default:
        return null;
    }
  }, [currentStep, data, updateData]);

  const isStepValid = useMemo(() => {
    if (currentStep === 1) return !!data.title?.trim() && !!data.logline?.trim();
    if (currentStep === 2) return (data.acts?.length || 0) >= 3;
    if (currentStep === 3) return (data.charactersUsed?.length || 0) > 0;
    return true;
  }, [currentStep, data]);

  return (
    <WizardErrorBoundary wizardType="storyteller">
      <div className="flex flex-col h-full max-w-6xl mx-auto">
        {/* Header Area */}
        <div className="px-8 pt-8 pb-4">
          <div className="flex justify-between items-start mb-8">
            <div>
              <h2 className="text-4xl font-black text-gray-900 dark:text-white tracking-tight flex items-center gap-3">
                Scenario Builder
                <span className="text-xs font-bold uppercase py-1 px-2 bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-300 rounded-md tracking-widest text-premium">Premium</span>
              </h2>
              <p className="text-gray-500 dark:text-gray-400 font-medium mt-1">
                Design multi-act structures and character arcs with ease.
              </p>
            </div>
            <button 
              onClick={onCancel}
              className="p-2 text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 transition-colors"
            >
              Cancel Build
            </button>
          </div>

          <WizardStepIndicator 
            steps={steps} 
            currentStep={currentStep} 
          />
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto px-8 py-4 custom-scrollbar">
          <div className="max-w-4xl mx-auto pb-12">
            {stepContent}
          </div>
        </div>

        {/* Navigation Area */}
        <div className="px-8 py-6 border-t border-gray-100 dark:border-gray-800 bg-white/50 dark:bg-gray-900/50 backdrop-blur-md">
          <div className="max-w-4xl mx-auto">
            <WizardNavigation
              currentStep={currentStep}
              totalSteps={steps.length}
              onNext={() => setCurrentStep((s) => s + 1)}
              onBack={() => setCurrentStep((s) => s - 1)}
              canGoNext={isStepValid}
              canGoBack={currentStep > 1}
              canSkip={false}
              onSkip={() => {}}
              onSaveDraft={() => {
                const success = saveWizardState('storyteller', currentStep, data);
                if (success) setLastSaved(new Date());
              }}
              onSubmit={handleFinish}
              lastSaved={lastSaved}
            />
          </div>
        </div>
      </div>
    </WizardErrorBoundary>
  );
}
