import React, { useState } from 'react';
import { Plus, Trash2, Sparkles, Shield, Cpu, Zap, Gavel, Scale } from 'lucide-react';
import { useWizard } from '@/contexts/WizardContext';
import type { World, WorldRule } from '@/types/world';
import { RULE_CATEGORIES, createEmptyWorldRule } from '@/types/world';
import { WizardFormLayout, FormField, FormSection } from '../WizardFormLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useLLMGeneration } from '@/hooks/useLLMGeneration';
import { LLMErrorDisplay, LLMLoadingState } from '../LLMErrorDisplay';
import { ServiceWarning, useServiceStatus } from '@/components/ui/service-warning';
import { useAppStore } from '@/stores/useAppStore';
import { useToast } from '@/hooks/use-toast';

// ============================================================================
// Step 2: Ontological Governance (World Rules)
// ============================================================================

export function Step2OntologicalGovernance() {
    const { formData, updateFormData } = useWizard<World>();
    const [expandedRuleId, setExpandedRuleId] = useState<string | null>(null);
    const { llmConfigured, llmChecking } = useServiceStatus();
    const setShowLLMSettings = useAppStore((state) => state.setShowLLMSettings);
    const { toast } = useToast();

    const {
        generate,
        isLoading,
        error: llmError,
        clearError,
    } = useLLMGeneration({
        onSuccess: (response) => {
            // Parse LLM response and add rules
            const generatedRules = parseLLMRules(response.content);
            if (generatedRules.length > 0) {
                updateFormData({ rules: [...rules, ...generatedRules] });
            }
        },
    });

    const rules = formData.rules || [];

    // ============================================================================
    // Rule Management
    // ============================================================================

    const handleAddRule = () => {
        const newRule = createEmptyWorldRule();
        updateFormData({ rules: [...rules, newRule] });
        setExpandedRuleId(newRule.id);
    };

    const handleRemoveRule = (ruleId: string) => {
        updateFormData({ rules: rules.filter((r) => r.id !== ruleId) });
        if (expandedRuleId === ruleId) {
            setExpandedRuleId(null);
        }
    };

    const handleUpdateRule = (ruleId: string, updates: Partial<WorldRule>) => {
        updateFormData({
            rules: rules.map((r) => (r.id === ruleId ? { ...r, ...updates } : r)),
        });
    };

    const toggleRuleExpanded = (ruleId: string) => {
        setExpandedRuleId(expandedRuleId === ruleId ? null : ruleId);
    };

    // ============================================================================
    // LLM Generation
    // ============================================================================

    const handleGenerateRules = async () => {
        clearError();

        // Provide helpful message if no genre selected
        if (!formData.genre?.length) {
            toast({
                title: 'System Framework Required',
                description: 'Please select at least one causal framework before generating protocols.',
                variant: 'warning',
            });
            return;
        }

        const context = {
            genre: formData.genre || [],
            timePeriod: formData.timePeriod || '',
            tone: formData.tone || [],
        };

        const systemPrompt = "You are an Ontological Governance Architect. Your objective is to formulate fundamental systemic constraints and governing protocols for a multi-layered reality. Ensure each protocol has clear causal implications within the manifested environment.";

        const prompt = `Generate 4-6 world rules for a story world with the following characteristics:
- Framework: ${context.genre.join(', ')}
- Coordinates: ${context.timePeriod}
- Experiential Parameters: ${context.tone.join(', ')}

For each rule, provide:
1. Category (physical, social, magical, or technological)
2. The Governance Identifier (concise name, technical feel)
3. Causal Impact (how this affects the manifested reality)

Format as JSON array:
[
  {
    "category": "physical",
    "rule": "ATMOSPHERIC_BIOLUMINESCENCE",
    "implications": "Natural light is generated by airborne spores. Sight-based technology is evolved around specific spectral frequencies."
  }
]`;

        await generate({
            prompt,
            systemPrompt,
            temperature: 0.8,
            maxTokens: 1500,
        });
    };

    const parseLLMRules = (response: string): WorldRule[] => {
        try {
            const jsonRegex = /\[[\s\S]*\]/;
            const jsonMatch = jsonRegex.exec(response);

            if (jsonMatch) {
                const parsed = JSON.parse(jsonMatch[0]);
                if (Array.isArray(parsed)) {
                    return parsed.map((item) => ({
                        id: crypto.randomUUID(),
                        category: item.category || 'physical',
                        rule: item.rule || item.name || '',
                        implications: item.implications || '',
                    })).filter(rule => rule.rule);
                }
            }

            return [];
        } catch (error) {
            console.error('Failed to parse rules:', error);
            return [];
        }
    };

    const getCategoryIcon = (category: string) => {
        switch (category) {
            case 'physical': return <Scale className="h-4 w-4" />;
            case 'social': return <Gavel className="h-4 w-4" />;
            case 'magical': return <Zap className="h-4 w-4" />;
            case 'technological': return <Cpu className="h-4 w-4" />;
            default: return <Shield className="h-4 w-4" />;
        }
    };

    const getCategoryLabel = (category: string) => {
        switch (category) {
            case 'physical': return 'Material Constraints';
            case 'social': return 'Social Cohesion Subroutines';
            case 'magical': return 'Anomalous Protocols';
            case 'technological': return 'Applied Singularity';
            default: return 'Generic Constraint';
        }
    };

    return (
        <WizardFormLayout
            title="Ontological Governance"
            description="Define the fundamental laws and systemic protocols that regulate this manifested reality"
        >
            {/* AI Generation Section */}
            <div className="space-y-4 mb-8 p-4 rounded-none border border-primary/20 bg-primary/5 backdrop-blur-sm relative overflow-hidden">
                <div className="absolute top-0 right-0 p-1 opacity-20 rotate-12">
                    <Scale className="w-10 h-10 text-primary" />
                </div>
                <div className="flex items-center justify-between relative z-10">
                    <div>
                        <h3 className="text-base font-bold text-primary neon-text uppercase tracking-widest text-[10px] font-mono mb-1">// Protocol Synthesis Engine</h3>
                        <p className="text-[10px] text-primary/60 uppercase tracking-wider">
                            Synthesize governing protocols based on ontological frameworks
                        </p>
                    </div>
                    <Button
                        onClick={handleGenerateRules}
                        disabled={isLoading || !formData.genre?.length || !llmConfigured}
                        className="gap-2 btn-neon bg-primary/10 text-primary border-primary/20 hover:bg-primary/20"
                        size="sm"
                    >
                        <Sparkles className="h-3.5 w-3.5" />
                        <span className="text-[10px] font-black uppercase tracking-widest">{isLoading ? 'Synthesizing...' : 'Initialize Protocols'}</span>
                    </Button>
                </div>

                {!llmChecking && !llmConfigured && (
                    <ServiceWarning
                        service="llm"
                        variant="inline"
                        onConfigure={() => setShowLLMSettings(true)}
                        className="bg-red-500/10 border-red-500/20 text-red-400"
                    />
                )}

                {isLoading && (
                    <LLMLoadingState message="Compiling ontological constraints..." />
                )}

                {llmError && (
                    <LLMErrorDisplay
                        error={llmError}
                        onRetry={handleGenerateRules}
                        onDismiss={() => clearError?.()}
                    />
                )}
            </div>

            {/* Rules List */}
            <FormSection
                title="Core Constraints"
                description="Establish the fundamental laws and systemic behaviors of the world"
            >
                <div className="space-y-4">
                    {rules.length === 0 ? (
                        <div className="text-center py-12 border border-primary/20 bg-primary/5 rounded-none backdrop-blur-sm relative overflow-hidden group">
                            <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                            <Shield className="h-10 w-10 mx-auto text-primary/20 mb-3" />
                            <p className="text-[10px] text-primary/40 mb-6 uppercase tracking-[0.2em] font-mono">
                                No active protocols detected in current reality manifest.
                            </p>
                            <Button onClick={handleAddRule} variant="ghost" className="text-[10px] font-black uppercase tracking-widest text-primary border border-primary/20 hover:bg-primary/10">
                                <Plus className="h-3.5 w-3.5 mr-2" />
                                Initialize First Protocol
                            </Button>
                        </div>
                    ) : (
                        <>
                            {rules.map((rule) => {
                                const isExpanded = expandedRuleId === rule.id;

                                return (
                                    <div key={rule.id} className="border border-primary/20 bg-primary/5 backdrop-blur-sm overflow-hidden relative transition-all hover:border-primary/40">
                                        <div
                                            className="p-4 cursor-pointer hover:bg-primary/5 transition-colors flex items-start justify-between gap-4"
                                            onClick={() => toggleRuleExpanded(rule.id)}
                                        >
                                            <div className="flex-1 text-left pt-1">
                                                <div className="flex items-center gap-2 mb-1">
                                                    <div className="text-primary/60">{getCategoryIcon(rule.category)}</div>
                                                    <span className="text-[10px] font-black text-primary/40 uppercase tracking-widest font-mono">
                                // {getCategoryLabel(rule.category)}
                                                    </span>
                                                </div>
                                                <h4 className="text-sm font-black text-primary uppercase tracking-wider font-mono">
                                                    {rule.rule || 'UNIDENTIFIED_PROTOCOL'}
                                                </h4>
                                                {rule.implications && !isExpanded && (
                                                    <p className="text-[10px] text-primary/60 mt-1 line-clamp-1 font-mono italic">
                                                        {rule.implications}
                                                    </p>
                                                )}
                                            </div>
                                            <div className="flex items-center gap-2">
                                                <Button
                                                    variant="ghost"
                                                    size="sm"
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        handleRemoveRule(rule.id);
                                                    }}
                                                    className="h-7 text-red-500/40 hover:text-red-500 hover:bg-red-500/10"
                                                    aria-label="Delete rule"
                                                >
                                                    <Trash2 className="h-3.5 w-3.5" />
                                                </Button>
                                            </div>
                                        </div>

                                        {isExpanded && (
                                            <div className="p-4 pt-0 space-y-6 border-t border-primary/10 bg-[#050b10]/40">
                                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-6">
                                                    <FormField
                                                        label="Governance Identifier"
                                                        name={`rule-${rule.id}-rule`}
                                                        required
                                                    >
                                                        <Input
                                                            value={rule.rule}
                                                            onChange={(e) => handleUpdateRule(rule.id, { rule: e.target.value })}
                                                            placeholder="e.g., GRAVITY_CONSTANT_A"
                                                            className="font-mono text-xs"
                                                        />
                                                    </FormField>

                                                    <FormField
                                                        label="Ontological Domain"
                                                        name={`rule-${rule.id}-category`}
                                                        required
                                                    >
                                                        <Select
                                                            value={rule.category}
                                                            onValueChange={(value) => handleUpdateRule(rule.id, { category: value as WorldRule['category'] })}
                                                        >
                                                            <SelectTrigger className="font-mono text-xs h-9">
                                                                <SelectValue placeholder="Category" />
                                                            </SelectTrigger>
                                                            <SelectContent className="bg-[#050b10] border-primary/30">
                                                                {RULE_CATEGORIES.map((cat) => (
                                                                    <SelectItem key={cat.value} value={cat.value} className="focus:bg-primary/20 focus:text-primary">
                                                                        <span className="flex items-center gap-2">
                                                                            {getCategoryIcon(cat.value)}
                                                                            <span className="uppercase tracking-widest text-[9px] font-black font-mono">{getCategoryLabel(cat.value)}</span>
                                                                        </span>
                                                                    </SelectItem>
                                                                ))}
                                                            </SelectContent>
                                                        </Select>
                                                    </FormField>
                                                </div>

                                                <FormField
                                                    label="Causal Iteration Impact"
                                                    name={`rule-${rule.id}-implications`}
                                                    helpText="Projected effects on the manifested experiential layer"
                                                >
                                                    <Textarea
                                                        value={rule.implications}
                                                        onChange={(e) => handleUpdateRule(rule.id, { implications: e.target.value })}
                                                        placeholder="Map the secondary causal impacts of this protocol..."
                                                        rows={3}
                                                        className="font-mono text-xs"
                                                    />
                                                </FormField>
                                            </div>
                                        )}
                                    </div>
                                );
                            })}

                            <Button
                                variant="ghost"
                                onClick={handleAddRule}
                                className="w-full py-8 border border-dashed border-primary/20 text-[10px] font-black uppercase tracking-[0.2em] text-primary/60 hover:text-primary hover:border-primary/40 hover:bg-primary/5 transition-all"
                            >
                                <Plus className="h-4 w-4 mr-2" />
                                Initialize New Governing Protocol
                            </Button>
                        </>
                    )}
                </div>
            </FormSection>
        </WizardFormLayout>
    );
}
