import React, { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardContent, CardDescription, CardFooter } from '../../ui/card';
import { Button } from '../../ui/button';
import { Input } from '../../ui/input';
import { Textarea } from '../../ui/textarea';
import { Label } from '../../ui/label';
import { Checkbox } from '../../ui/checkbox';
import { Badge } from '../../ui/badge';
import { Progress } from '../../ui/progress';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '../../ui/tabs';
import { useStore } from '../../../store';
import { Share2, Youtube, Music2, Instagram, Twitter, Send, CheckCircle2, AlertCircle, Clock, History as HistoryIcon, Wand2, Zap, Layout, FileText, Image as ImageIcon, Calendar, Smartphone, ExternalLink, Trash2 } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '../../../components/ui/dialog';
import { useAddonVoiceCommands } from '../../../hooks/useAddonVoiceCommands';
import { videoPublisherService } from '@/services/VideoPublisherService';
import { useCharacterStore } from '@/stores/characterStore';
import { toast } from '@/hooks/use-toast';

export interface PlatformMetadata {
  title: string;
  description: string;
  tags: string;
  thumbnail_url?: string;
}

export interface HistoryItem {
  id: string;
  project_name: string;
  platform: string;
  status: 'published' | 'scheduled' | 'error';
  date: string;
  url: string;
  reach: number;
}

export interface Platform {
  id: string;
  name: string;
  status: 'connected' | 'disconnected' | 'error';
  username?: string;
}

export interface VideoPublisherEditorProps {
  isOpen: boolean;
  onClose: () => void;
}

// Assuming ProjectData, PlatformConfig, SocialMetadata types based on context
// These types would ideally be imported or defined elsewhere in a real application
interface ProjectData {
  id: string;
  project_name: string;
  // ... other project properties
}

interface PlatformConfig {
  // ... platform configuration properties
}

interface SocialMetadata {
  title: string;
  description: string;
  tags: string;
  thumbnail_url?: string;
}

export const VideoPublisherEditor: React.FC<VideoPublisherEditorProps> = ({ isOpen, onClose }) => {
  const project = useStore((state) => state.project);

  // Helper function for fallback metadata
  const getFallbackMetadata = (project: ProjectData, _config?: PlatformConfig): SocialMetadata => {
    return {
      title: project.project_name || 'My Story',
      description: 'Generated by StoryCore Engine AI #AI #Storytelling',
      tags: 'story, ai, video',
    };
  };

  const [title, setTitle] = useState(project?.project_name || '');
  const [description, setDescription] = useState('Generated by StoryCore Engine AI #AI #Storytelling');
  const [tags, setTags] = useState('story, ai, video');
  const [selectedPlatforms, setSelectedPlatforms] = useState<string[]>([]);
  const [platforms, setPlatforms] = useState<Platform[]>([]);
  const [isPublishing, setIsPublishing] = useState(false);
  const [publishProgress, setPublishProgress] = useState(0);
  const [status, setStatus] = useState<'idle' | 'publishing' | 'completed' | 'error'>('idle');

  // Voice Command Integration
  useAddonVoiceCommands({
    addonId: 'video-publisher',
    onGenerate: () => {
      toast({ title: 'Voice Assist', description: 'Generating AI metadata for all platforms...' });
      handleGenerateAI();
    },
    onExport: () => {
      toast({ title: 'Voice Assist', description: 'Starting viral distribution sequence...' });
      handlePublish();
    },
    onCancel: () => {
      toast({ title: 'Voice Assist', description: 'Closing Social Hub.' });
      onClose();
    },
    onEdit: () => {
      toast({ title: 'Voice Assist', description: 'Toggling mobile simulation preview.' });
      setShowPreview(prev => !prev);
    },
    onStatus: () => {
      toast({ title: 'Status', description: `Social Hub is ${status}. Reach: 12.4K.` });
    }
  });
  const [platformMetadata, setPlatformMetadata] = useState<Record<string, { title: string; description: string; tags: string; thumbnail_url?: string }>>({});
  const [activeMetadataTab, setActiveMetadataTab] = useState<string>('global');
  const [isGeneratingAI, setIsGeneratingAI] = useState(false);
  const [isScheduled, setIsScheduled] = useState(false);
  const [scheduleDate, setScheduleDate] = useState<string>('');
  const [scheduleTime, setScheduleTime] = useState<string>('');
  const [history] = useState<HistoryItem[]>([
    {
      id: '1',
      project_name: 'Cyberpunk Cityscape',
      platform: 'youtube_shorts',
      status: 'published',
      date: '2024-03-01 14:30',
      url: 'https://youtube.com/shorts/xyz123',
      reach: 1240
    },
    {
      id: '2',
      project_name: 'Neon Nights',
      platform: 'tiktok',
      status: 'published',
      date: '2024-02-28 09:15',
      url: 'https://tiktok.com/@user/video/789',
      reach: 3500
    }
  ]);
  const [showPreview, setShowPreview] = useState(false);
  const [previewPlatform, setPreviewPlatform] = useState<string>('youtube_shorts');

  const fetchPlatforms = async () => {
    try {
      const response = await fetch('/api/addons/video_publisher/platforms');
      if (response.ok) {
        const data = await response.json();
        setPlatforms(data);
        // Select connected platforms by default
        setSelectedPlatforms(data.filter((p: Platform) => p.status === 'connected').map((p: Platform) => p.id));
      } else {
        // Mock data for development if API is not available
        const mockPlatforms: Platform[] = [
          { id: 'youtube_shorts', name: 'YouTube Shorts', status: 'connected', username: '@StoryCore_AI' },
          { id: 'tiktok', name: 'TikTok', status: 'connected', username: 'storycore_official' },
          { id: 'instagram_reels', name: 'Instagram Reels', status: 'disconnected' },
          { id: 'x_twitter', name: 'X (Twitter)', status: 'connected', username: 'StoryCoreEngine' }
        ];
        setPlatforms(mockPlatforms);
        setSelectedPlatforms(mockPlatforms.filter(p => p.status === 'connected').map(p => p.id));
      }
    } catch (error) {
      console.error('Error fetching platforms:', error);
      // Fallback mock
      const mockPlatforms: Platform[] = [
        { id: 'youtube_shorts', name: 'YouTube Shorts', status: 'connected', username: '@StoryCore_AI' },
        { id: 'tiktok', name: 'TikTok', status: 'connected', username: 'storycore_official' },
      ];
      setPlatforms(mockPlatforms);
      setSelectedPlatforms(mockPlatforms.map(p => p.id));
    }
  };

  useEffect(() => {
    if (isOpen) {
      fetchPlatforms();
    }
  }, [isOpen]);

  const handleTogglePlatform = (id: string) => {
    setSelectedPlatforms((prev) =>
      prev.includes(id) ? prev.filter((p) => p !== id) : [...prev, id]
    );
  };

  const handleGenerateAI = async () => {
    if (!project) return;
    setIsGeneratingAI(true);
    try {
      // 1. Récupérer les personnages du store pour le contexte de l'IA
      const characters = useCharacterStore.getState().characters;
      
      // 2. Générer pour chaque plateforme connectée + global
      const newMetadata: Record<string, PlatformMetadata> = {};
      const targetPlatforms = ['global', ...selectedPlatforms];
      
      for (const pId of targetPlatforms) {
        toast({ title: 'AI Analyst', description: `Optimizing metadata for ${pId}...` });
        const meta = await videoPublisherService.generateViralMetadata(project as any, characters, pId);
        
        newMetadata[pId] = {
          title: meta.title,
          description: meta.description,
          tags: meta.hashtags.join(', '),
          thumbnail_url: meta.thumbnailPrompt // Note: on utilise ici le prompt de thumbnail
        };
      }
      
      setPlatformMetadata(newMetadata);
      
      // Update global fields
      const global = newMetadata['global'];
      if (global) {
        setTitle(global.title);
        setDescription(global.description);
        setTags(global.tags);
      }
      
      toast({ title: 'Success', description: 'Viral metadata generated successfully!' });
    } catch (error) {
      console.error('AI generation failed', error);
      toast({ title: 'Error', variant: 'destructive', description: 'AI was unable to generate metadata.' });
    } finally {
      setIsGeneratingAI(false);
    }
  };

  const handlePublish = async () => {
    if (!project || selectedPlatforms.length === 0) return;

    setIsPublishing(true);
    setStatus('publishing');
    setPublishProgress(0);

    const overrides: Record<string, { title: string; description: string; tags: string[]; thumbnail_url?: string }> = {};
    selectedPlatforms.forEach(p => {
      if (platformMetadata[p]) {
        overrides[p] = {
          ...platformMetadata[p],
          tags: platformMetadata[p].tags.split(',').map(t => t.trim())
        };
      }
    });

    try {
      const response = await fetch('/api/addons/video_publisher/publish', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          project_id: project.id,
          video_path: 'exports/final_render.mp4',
          title,
          description,
          tags: tags.split(',').map(t => t.trim()),
          platforms: selectedPlatforms,
          overrides
        })
      });

      if (!response.ok) {
        setTimeout(() => {
          simulatePublishProgress();
        }, 500);
        return;
      }

      const _result = await response.json();
      simulatePublishProgress();
    } catch (_error) {
      console.warn('Backend not available, simulating publish progress');
      simulatePublishProgress();
    }
  };

  const simulatePublishProgress = () => {
    let progress = 0;
    const interval = setInterval(() => {
      progress += Math.floor(Math.random() * 15) + 5;
      if (progress >= 100) {
        progress = 100;
        setPublishProgress(100);
        setStatus('completed');
        setIsPublishing(false);
        clearInterval(interval);
      } else {
        setPublishProgress(progress);
      }
    }, 800);
  };

  const getPlatformIcon = (id: string) => {
    switch (id) {
      case 'youtube_shorts': return <Youtube className="w-4 h-4 text-red-500" />;
      case 'tiktok': return <Music2 className="w-4 h-4 text-pink-500" />;
      case 'instagram_reels': return <Instagram className="w-4 h-4 text-purple-500" />;
      case 'x_twitter': return <Twitter className="w-4 h-4 text-blue-400" />;
      default: return <Share2 className="w-4 h-4" />;
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-5xl h-[90vh] overflow-hidden flex flex-col bg-background/95 backdrop-blur-xl border-primary/20 shadow-2xl">
        <DialogHeader className="flex-shrink-0 pb-4 border-b border-border/50">
          <div className="flex items-center justify-between pr-8">
            <div>
              <DialogTitle className="text-3xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-primary to-purple-400">
                Social Hub
              </DialogTitle>
              <p className="text-muted-foreground text-sm mt-1">Publish your stories across all platforms in one click.</p>
            </div>
            <Badge variant="secondary" className="px-3 py-1 gap-1.5 font-medium bg-primary/10 text-primary border-primary/20">
              <Share2 className="w-3.5 h-3.5" />
              Powered by PostBot Protocol
            </Badge>
          </div>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto p-1 custom-scrollbar">
          <Tabs defaultValue="publish" className="w-full">
            <TabsList className="grid w-full grid-cols-2 lg:w-[400px] mb-6">
              <TabsTrigger value="publish" className="gap-2">
                <Send className="w-4 h-4" /> Publish
              </TabsTrigger>
              <TabsTrigger value="history" className="gap-2">
                <HistoryIcon className="w-4 h-4" /> History
              </TabsTrigger>
            </TabsList>

            <TabsContent value="publish" className="space-y-6 animate-in fade-in slide-in-from-bottom-2 duration-300">
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 pb-6">
                {/* Metadata Section */}
                <div className="lg:col-span-2 space-y-6">
                  <Card className="border-primary/10 bg-card/30 backdrop-blur-sm shadow-sm ring-1 ring-white/5 overflow-hidden">
                    <CardHeader className="flex flex-row items-center justify-between pb-2">
                      <div>
                        <CardTitle className="text-lg">Content Details</CardTitle>
                        <CardDescription>How your video will appear to your audience.</CardDescription>
                      </div>
                      <Button 
                        size="sm" 
                        variant="ghost" 
                        className="gap-2 text-primary hover:bg-primary/10 hover:text-primary transition-all font-bold"
                        onClick={handleGenerateAI}
                        disabled={isGeneratingAI}
                      >
                        {isGeneratingAI ? (
                          <div className="w-4 h-4 border-2 border-primary/30 border-t-primary rounded-full animate-spin" />
                        ) : (
                          <Wand2 className="w-4 h-4" />
                        )}
                        AI Magic
                      </Button>
                    </CardHeader>
                    
                    <div className="px-6 border-b border-border/50">
                      <Tabs value={activeMetadataTab} onValueChange={setActiveMetadataTab} className="w-full">
                        <TabsList className="bg-transparent h-10 w-full justify-start gap-1 p-0 overflow-x-auto no-scrollbar">
                          <TabsTrigger 
                            value="global" 
                            className="bg-transparent data-[state=active]:bg-transparent data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none px-4 h-full text-xs font-bold transition-none"
                          >
                            <Layout className="w-3.5 h-3.5 mr-2" /> Global
                          </TabsTrigger>
                          <TabsTrigger 
                            value="search" 
                            className="bg-transparent data-[state=active]:bg-transparent data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none px-4 h-full text-xs font-bold transition-none"
                          >
                            <ExternalLink className="w-3.5 h-3.5 mr-2" /> Search Engine
                          </TabsTrigger>
                          {selectedPlatforms.map(p => (
                            <TabsTrigger 
                              key={p} 
                              value={p} 
                              className="bg-transparent data-[state=active]:bg-transparent data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none px-4 h-full text-xs font-bold transition-none"
                            >
                              <div className="flex items-center gap-2">
                                {getPlatformIcon(p)}
                                {platforms.find(pl => pl.id === p)?.name}
                              </div>
                            </TabsTrigger>
                          ))}
                        </TabsList>
                      </Tabs>
                    </div>

                    <CardContent className="space-y-5 pt-4">
                      {activeMetadataTab === 'global' ? (
                        <>
                          <div className="space-y-2">
                            <Label htmlFor="title" className="text-sm font-semibold flex items-center gap-2">
                              <FileText className="w-3.5 h-3.5 text-muted-foreground" />
                              Global Title
                            </Label>
                            <Input 
                              id="title" 
                              value={title} 
                              onChange={(e) => setTitle(e.target.value)}
                              placeholder="Enter a catchy title..."
                              className="bg-background/50 border-border/50 focus:border-primary/50 transition-all font-medium"
                            />
                          </div>
                          <div className="space-y-2">
                            <Label htmlFor="description" className="text-sm font-semibold flex items-center gap-2">
                              <Zap className="w-3.5 h-3.5 text-muted-foreground" />
                              Global Description
                            </Label>
                            <Textarea 
                              id="description" 
                              value={description} 
                              onChange={(e) => setDescription(e.target.value)}
                              placeholder="Write your story's description..."
                              rows={5}
                              className="bg-background/50 border-border/50 focus:border-primary/50 transition-all resize-none font-medium"
                            />
                          </div>
                          <div className="space-y-2">
                            <Label htmlFor="tags" className="text-sm font-semibold">Hashtags</Label>
                            <Input 
                              id="tags" 
                              value={tags} 
                              onChange={(e) => setTags(e.target.value)}
                              placeholder="ai, story, animation..."
                              className="bg-background/50 border-border/50 focus:border-primary/50 transition-all font-medium"
                            />
                          </div>
                        </>
                      ) : activeMetadataTab === 'search' ? (
                        <div className="space-y-6 animate-in fade-in duration-300 py-4">
                          <div className="space-y-2">
                            <h4 className="text-xs font-bold uppercase tracking-widest text-muted-foreground mb-4">Google Search Preview</h4>
                            <div className="p-6 bg-white rounded-xl border border-border shadow-sm max-w-2xl">
                              <div className="text-[14px] text-[#202124] font-medium truncate mb-1">
                                https://storycore.ai/projects/{project?.id?.substring(0,8)}
                              </div>
                              <div className="text-[20px] text-[#1a0dab] font-normal hover:underline cursor-pointer mb-1">
                                {platformMetadata['search']?.title || title}
                              </div>
                              <div className="text-[14px] text-[#4d5156] leading-relaxed">
                                <span className="text-[#70757a]">21 oct. 2026 — </span>
                                {platformMetadata['search']?.description || description}
                              </div>
                            </div>
                          </div>
                          
                          <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                              <Label className="text-xs font-bold">SEO Title Override</Label>
                              <Input 
                                value={platformMetadata['search']?.title || ''} 
                                onChange={(e) => setPlatformMetadata({
                                  ...platformMetadata,
                                  ['search']: { ...platformMetadata['search'], title: e.target.value }
                                })}
                                className="h-8 text-xs"
                                placeholder={title}
                              />
                            </div>
                            <div className="space-y-2">
                              <Label className="text-xs font-bold">SEO Description Override</Label>
                              <Input 
                                value={platformMetadata['search']?.description || ''} 
                                onChange={(e) => setPlatformMetadata({
                                  ...platformMetadata,
                                  ['search']: { ...platformMetadata['search'], description: e.target.value }
                                })}
                                className="h-8 text-xs"
                                placeholder={description}
                              />
                            </div>
                          </div>
                        </div>
                      ) : (
                        <div className="space-y-5 animate-in fade-in duration-300">
                          <div className="flex gap-4">
                            <div className="flex-1 space-y-4">
                              <div className="space-y-2">
                                <Label className="text-sm font-semibold flex items-center gap-2 text-primary">
                                  {getPlatformIcon(activeMetadataTab)}
                                  {platforms.find(pl => pl.id === activeMetadataTab)?.name} Title
                                </Label>
                                <Input 
                                  value={platformMetadata[activeMetadataTab]?.title || ''} 
                                  onChange={(e) => {
                                    setPlatformMetadata({
                                      ...platformMetadata,
                                      [activeMetadataTab]: { ...platformMetadata[activeMetadataTab], title: e.target.value }
                                    });
                                  }}
                                  className="bg-background/50 border-primary/20 focus:border-primary transition-all font-bold"
                                />
                              </div>
                              <div className="space-y-2">
                                <Label className="text-sm font-semibold">Description Override</Label>
                                <Textarea 
                                  value={platformMetadata[activeMetadataTab]?.description || ''} 
                                  onChange={(e) => {
                                    setPlatformMetadata({
                                      ...platformMetadata,
                                      [activeMetadataTab]: { ...platformMetadata[activeMetadataTab], description: e.target.value }
                                    });
                                  }}
                                  rows={4}
                                  className="bg-background/50 border-primary/20 focus:border-primary transition-all resize-none text-xs"
                                />
                              </div>
                            </div>
                            <div className="w-32 lg:w-48 space-y-2">
                              <Label className="text-sm font-semibold flex items-center gap-2">
                                <ImageIcon className="w-3.5 h-3.5" />
                                Thumbnail
                              </Label>
                              <div className="aspect-[9/16] lg:aspect-video bg-muted rounded-xl border border-dashed border-border/50 overflow-hidden relative group">
                                {platformMetadata[activeMetadataTab]?.thumbnail_url ? (
                                  <img 
                                    src={platformMetadata[activeMetadataTab]?.thumbnail_url} 
                                    alt="Platform Thumbnail" 
                                    className="w-full h-full object-cover"
                                  />
                                ) : (
                                  <div className="absolute inset-0 flex flex-col items-center justify-center text-[10px] text-muted-foreground p-2 text-center">
                                    <ImageIcon className="w-6 h-6 mb-2 opacity-20" />
                                    Wait for AI Generation
                                  </div>
                                )}
                              </div>
                            </div>
                          </div>
                        </div>
                      )}
                    </CardContent>
                  </Card>

                  {status !== 'idle' && (
                    <Card className="border-primary/30 bg-primary/5 shadow-inner overflow-hidden">
                      <CardContent className="pt-6">
                        <div className="space-y-4">
                          <div className="flex items-center justify-between">
                            <div className="flex items-center gap-3">
                              {status === 'publishing' && (
                                <div className="relative">
                                  <Clock className="w-5 h-5 text-primary animate-pulse" />
                                  <div className="absolute inset-0 bg-primary/20 blur-md rounded-full animate-pulse" />
                                </div>
                              )}
                              {status === 'completed' && <CheckCircle2 className="w-5 h-5 text-green-500" />}
                              {status === 'error' && <AlertCircle className="w-5 h-5 text-destructive" />}
                              <span className="font-bold text-sm tracking-tight text-foreground/90">
                                {status === 'publishing' ? 'Synchronizing across platforms...' : 
                                 status === 'completed' ? 'Successfully published to all platforms!' : 
                                 'Something went wrong.'}
                              </span>
                            </div>
                            <span className="text-xs font-mono font-bold px-2 py-0.5 rounded bg-background/50 border border-border/50">
                              {publishProgress}%
                            </span>
                          </div>
                          <Progress value={publishProgress} className="h-2.5 bg-primary/20" />
                          {status === 'completed' && (
                            <div className="grid grid-cols-2 lg:grid-cols-4 gap-2 pt-2 animate-in zoom-in-95 duration-500">
                              {selectedPlatforms.map(p => (
                                <Button key={p} variant="secondary" size="sm" className="gap-2 h-9 text-xs font-medium hover:bg-primary/20 transition-colors">
                                  {getPlatformIcon(p)} View Post
                                </Button>
                              ))}
                            </div>
                          )}
                        </div>
                      </CardContent>
                    </Card>
                  )}
                </div>

                {/* Platforms Section */}
                <div className="space-y-6">
                  <Card className="border-border/50 shadow-sm overflow-hidden">
                    <CardHeader className="bg-muted/30 pb-4">
                      <CardTitle className="text-lg flex items-center gap-2">
                        <Share2 className="w-4 h-4 text-primary" /> Destination
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-3 pt-4">
                      {platforms.map((platform) => (
                        <div 
                          key={platform.id} 
                          className={`flex items-center justify-between p-3 border rounded-xl transition-all ${
                            selectedPlatforms.includes(platform.id) 
                              ? 'bg-primary/5 border-primary/30 ring-1 ring-primary/20' 
                              : 'hover:bg-accent/50 border-border/50'
                          }`}
                        >
                          <div className="flex items-center gap-3">
                            <div className="p-2 bg-background rounded-lg shadow-sm ring-1 ring-black/5">
                              {getPlatformIcon(platform.id)}
                            </div>
                            <div>
                              <p className="text-xs font-bold leading-none mb-1">{platform.name}</p>
                              <p className="text-[10px] uppercase font-bold tracking-wider">
                                {platform.status === 'connected' ? (
                                  <span className="text-green-500">{platform.username}</span>
                                ) : (
                                  <span className="text-muted-foreground/60 italic">Disconnected</span>
                                )}
                              </p>
                            </div>
                          </div>
                          <Checkbox 
                            checked={selectedPlatforms.includes(platform.id)}
                            onCheckedChange={() => handleTogglePlatform(platform.id)}
                            disabled={platform.status !== 'connected' || isPublishing}
                            className="rounded-full w-5 h-5"
                          />
                        </div>
                      ))}
                    </CardContent>
                    <CardFooter className="pt-2">
                      <Button 
                        className={`w-full h-12 gap-3 text-sm font-bold shadow-xl transition-all active:scale-95 ${
                          isPublishing 
                            ? 'bg-muted cursor-not-allowed opacity-70' 
                            : 'bg-primary hover:bg-primary/90 shadow-primary/20'
                        }`} 
                        onClick={handlePublish}
                        disabled={isPublishing || selectedPlatforms.length === 0}
                      >
                        {isPublishing ? (
                          <>
                            <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                            Pushing to Cloud...
                          </>
                        ) : (
                          <>
                            <Send className="w-4 h-4" /> 
                            Go Viral Now
                          </>
                        )}
                      </Button>
                    </CardFooter>
                  </Card>

                  <Card className="border-border/50 shadow-sm overflow-hidden bg-background/40">
                    <CardHeader className="bg-muted/30 pb-4 flex flex-row items-center justify-between">
                      <CardTitle className="text-lg flex items-center gap-2">
                        <Calendar className="w-4 h-4 text-primary" /> Scheduling
                      </CardTitle>
                      <Checkbox 
                        checked={isScheduled} 
                        onCheckedChange={(checked) => setIsScheduled(checked === true)}
                        className="rounded-full"
                      />
                    </CardHeader>
                    <CardContent className={`pt-4 transition-all duration-300 ${isScheduled ? 'opacity-100' : 'opacity-40 grayscale pointer-events-none'}`}>
                      <div className="space-y-4">
                        <div className="grid grid-cols-2 gap-2">
                          <div className="space-y-1.5">
                            <Label className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Date</Label>
                            <Input 
                              type="date" 
                              value={scheduleDate} 
                              onChange={(e) => setScheduleDate(e.target.value)}
                              className="text-xs h-9 bg-background/50"
                            />
                          </div>
                          <div className="space-y-1.5">
                            <Label className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Time</Label>
                            <Input 
                              type="time" 
                              value={scheduleTime} 
                              onChange={(e) => setScheduleTime(e.target.value)}
                              className="text-xs h-9 bg-background/50"
                            />
                          </div>
                        </div>
                        <div className="p-2 rounded-lg bg-primary/5 border border-primary/20 flex items-start gap-2">
                          <Clock className="w-3.5 h-3.5 text-primary mt-0.5" />
                          <p className="text-[10px] leading-snug">
                            Posts will be automatically published using localized peak-hour algorithms for maximum engagement.
                          </p>
                        </div>
                      </div>
                    </CardContent>
                  </Card>

                  <Card className="bg-gradient-to-br from-primary/10 via-purple-500/10 to-blue-500/10 border-none shadow-sm overflow-hidden relative group">
                    <div className="absolute inset-0 bg-white/5 opacity-0 group-hover:opacity-100 transition-opacity" />
                    <CardContent className="pt-6 space-y-3">
                      <h4 className="font-bold text-sm flex items-center gap-2">
                        <Share2 className="w-4 h-4 text-primary" /> Cross-Post Stats
                      </h4>
                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-0.5">
                          <p className="text-[10px] font-bold text-muted-foreground uppercase opacity-70">Weekly Reach</p>
                          <p className="text-2xl font-black tracking-tight">12.4K</p>
                        </div>
                        <div className="space-y-0.5">
                          <p className="text-[10px] font-bold text-muted-foreground uppercase opacity-70">Platforms</p>
                          <p className="text-2xl font-black tracking-tight">{platforms.filter(p => p.status === 'connected').length}</p>
                        </div>
                      </div>
                      <div className="pt-2">
                        <div className="w-full bg-black/10 h-10 rounded-lg flex items-center justify-center text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                          Insights coming soon
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </div>
            </TabsContent>

            <TabsContent value="history" className="animate-in fade-in slide-in-from-bottom-2 duration-300">
              <div className="space-y-4">
                {history.map((item) => (
                  <Card key={item.id} className="border-border/50 bg-card/30 backdrop-blur-sm overflow-hidden group hover:border-primary/30 transition-all">
                    <CardContent className="p-4 flex items-center justify-between">
                      <div className="flex items-center gap-4">
                        <div className="w-12 h-16 bg-muted rounded-md overflow-hidden flex-shrink-0 relative">
                          <img src={`https://picsum.photos/seed/${item.id}/200/300`} alt="Project thumbnail" className="w-full h-full object-cover opacity-50" />
                          <div className="absolute inset-0 flex items-center justify-center">
                            {getPlatformIcon(item.platform)}
                          </div>
                        </div>
                        <div>
                          <h4 className="font-bold text-sm">{item.project_name}</h4>
                          <div className="flex items-center gap-2 mt-1">
                            <Badge variant="outline" className="text-[10px] h-4 font-mono">{item.date}</Badge>
                            <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                              <Zap className="w-3 h-3 text-yellow-500" /> {item.reach.toLocaleString()} views
                            </span>
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <Button variant="ghost" size="icon" className="h-8 w-8 hover:bg-primary/20 hover:text-primary" asChild>
                          <a href={item.url} target="_blank" rel="noreferrer">
                            <ExternalLink className="w-4 h-4" />
                          </a>
                        </Button>
                        <Button variant="ghost" size="icon" className="h-8 w-8 hover:bg-destructive/20 hover:text-destructive">
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))}
                
                {history.length === 0 && (
                  <Card className="border-dashed bg-transparent border-border/50">
                    <CardContent className="flex flex-col items-center justify-center py-20 text-muted-foreground">
                      <div className="relative mb-6">
                        <HistoryIcon className="w-16 h-16 opacity-10" />
                        <div className="absolute inset-0 blur-2xl bg-primary/20 rounded-full opacity-20" />
                      </div>
                      <h3 className="text-lg font-semibold text-foreground/70 mb-1">No Activity Yet</h3>
                      <p className="text-sm max-w-[250px] text-center">Your publishing history will appear here once you go live!</p>
                    </CardContent>
                  </Card>
                )}
              </div>
            </TabsContent>
          </Tabs>
        </div>

        {/* Floating Preview Phone (Subtle UI for wowed factor) */}
        <div className="hidden xl:flex absolute right-[-100px] top-1/2 -translate-y-1/2 flex-col gap-4 animate-in slide-in-from-right duration-700">
           <Button 
            variant="outline" 
            className="rounded-full w-12 h-12 p-0 bg-background/80 backdrop-blur-md shadow-xl border-primary/20 hover:border-primary/50 transition-all text-primary"
            onClick={() => {
              setPreviewPlatform(selectedPlatforms[0] || 'youtube_shorts');
              setShowPreview(!showPreview);
            }}
          >
            <Smartphone className="w-5 h-5" />
          </Button>
        </div>

        {showPreview && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm animate-in fade-in duration-300">
            <div className="relative w-[320px] h-[640px] bg-black rounded-[2.5rem] border-8 border-[#1a1a1a] shadow-2xl overflow-hidden ring-4 ring-white/5">
              {/* Notch */}
              <div className="absolute top-0 left-1/2 -translate-x-1/2 w-32 h-6 bg-[#1a1a1a] rounded-b-2xl z-20" />
              
              {/* Internal Content (Mobile Mockup) */}
              <div className="w-full h-full relative bg-gray-900 flex flex-col pt-10">
                <div className="flex-1 relative overflow-hidden bg-black flex items-center justify-center">
                   {/* Mock Video BG */}
                   <img 
                     src={`https://picsum.photos/seed/${project?.id}/400/800`} 
                     className="w-full h-full object-cover opacity-80" 
                     alt={`Mobile preview for ${project?.project_name || 'project'}`}
                     title={`Preview for ${project?.project_name || 'current project'}`}
                   />
                   <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/20" />
                   
                   {/* UI Overlay based on Platform */}
                   <div className="absolute inset-0 p-4 flex flex-col justify-end text-white pb-10">
                      <div className="flex items-center gap-2 mb-3">
                         <div className="w-8 h-8 rounded-full bg-primary/20 border border-primary/40" />
                         <span className="text-sm font-bold">@StoryCore_AI</span>
                         <Badge variant="outline" className="text-[10px] h-4 text-white border-white/50">Follow</Badge>
                      </div>
                      <h4 className="text-sm font-bold mb-1 truncate">
                        {platformMetadata[previewPlatform]?.title || title}
                      </h4>
                      <p className="text-xs text-white/80 line-clamp-2 mb-3">
                        {platformMetadata[previewPlatform]?.description || description}
                      </p>
                      <div className="flex gap-2 text-[10px] font-bold text-primary">
                        {(platformMetadata[previewPlatform]?.tags || tags).split(',').slice(0, 3).map(t => (
                          <span key={t}>#{t.trim()}</span>
                        ))}
                      </div>
                   </div>

                   {/* Vertical Actions */}
                   <div className="absolute right-3 bottom-20 flex flex-col gap-5 items-center">
                      <div className="flex flex-col items-center gap-1">
                        <div className="w-10 h-10 rounded-full bg-white/10 backdrop-blur-md flex items-center justify-center overflow-hidden border border-white/10 group-hover:bg-white/20 transition-all">
                           <Zap className="w-5 h-5 fill-white" />
                        </div>
                        <span className="text-[10px] font-bold">12.4K</span>
                      </div>
                      <div className="flex flex-col items-center gap-1">
                        <div className="w-10 h-10 rounded-full bg-white/10 backdrop-blur-md flex items-center justify-center">
                           <Layout className="w-5 h-5" />
                        </div>
                        <span className="text-[10px] font-bold">452</span>
                      </div>
                      <div className="flex flex-col items-center gap-1">
                        <div className="w-10 h-10 rounded-full bg-white/10 backdrop-blur-md flex items-center justify-center">
                           <Share2 className="w-5 h-5" />
                        </div>
                        <span className="text-[10px] font-bold">Share</span>
                      </div>
                   </div>
                </div>

                {/* Platform Switcher inside phone */}
                <div className="h-14 bg-black/90 p-2 border-t border-white/5 flex items-center justify-around">
                   {selectedPlatforms.slice(0, 4).map(p => (
                     <button 
                        key={p}
                        className={`p-1.5 rounded-lg transition-all ${previewPlatform === p ? 'bg-primary/20 ring-1 ring-primary' : 'opacity-40'}`}
                        onClick={() => setPreviewPlatform(p)}
                      >
                        {getPlatformIcon(p)}
                     </button>
                   ))}
                </div>
              </div>

              {/* Close Button UI */}
              <Button 
                variant="ghost" 
                size="icon" 
                className="absolute top-2 right-2 text-white/50 hover:text-white z-50 h-8 w-8"
                onClick={() => setShowPreview(false)}
              >
                <Trash2 className="w-4 h-4 rotate-45" />
              </Button>
            </div>
            
            <div className="absolute bottom-10 flex flex-col items-center gap-2 text-white/60">
               <p className="text-xs font-medium bg-black/40 px-3 py-1 rounded-full backdrop-blur-md border border-white/10">
                 Tap to exit preview
               </p>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
};

export default VideoPublisherEditor;
